zone_1_arm:
  description: Send a request to Olarm to arm area 1 on your alarm.

zone_1_sleep:
  description: Send a request to Olarm to set area 1 to sleep on your alarm.

zone_1_stay:
  description: Send a request to Olarm to set area 1 to stay on your alarm.

zone_1_disarm:
  description: Send a request to Olarm to disarm area 1 of your alarm.

zone_2_arm:
  description: Send a request to Olarm to arm area 2 on your alarm.

zone_2_sleep:
  description: Send a request to Olarm to set area 2 to sleep on your alarm.

zone_2_stay:
  description: Send a request to Olarm to set area 2 to stay on your alarm.

zone_2_disarm:
  description: Send a request to Olarm to disarm area 2 of your alarm.

zone_3_arm:
  description: Send a request to Olarm to arm area 3 on your alarm.

zone_3_sleep:
  description: Send a request to Olarm to set area 3 to sleep on your alarm.

zone_3_stay:
  description: Send a request to Olarm to set area 3 to stay on your alarm.

zone_3_disarm:
  description: Send a request to Olarm to disarm area 3 of your alarm.

zone_4_arm:
  description: Send a request to Olarm to arm area 4 on your alarm.

zone_4_sleep:
  description: Send a request to Olarm to set area 4 to sleep on your alarm.

zone_4_stay:
  description: Send a request to Olarm to set area 4 to stay on your alarm.

zone_4_disarm:
  description: Send a request to Olarm to disarm area 4 of your alarm.

zone_5_arm:
  description: Send a request to Olarm to arm area 5 on your alarm.

zone_5_sleep:
  description: Send a request to Olarm to set area 5 to sleep on your alarm.

zone_5_stay:
  description: Send a request to Olarm to set area 5 to stay on your alarm.

zone_5_disarm:
  description: Send a request to Olarm to disarm area 5 of your alarm.

zone_6_arm:
  description: Send a request to Olarm to arm area 6 on your alarm.

zone_6_sleep:
  description: Send a request to Olarm to set area 6 to sleep on your alarm.

zone_6_stay:
  description: Send a request to Olarm to set area 6 to stay on your alarm.

zone_6_disarm:
  description: Send a request to Olarm to disarm area 6 of your alarm.

zone_7_arm:
  description: Send a request to Olarm to arm area 7 on your alarm.

zone_7_sleep:
  description: Send a request to Olarm to set area 7 to sleep on your alarm.

zone_7_stay:
  description: Send a request to Olarm to set area 7 to stay on your alarm.

zone_7_disarm:
  description: Send a request to Olarm to disarm area 7 of your alarm.

zone_8_arm:
  description: Send a request to Olarm to arm area 8 on your alarm.

zone_8_sleep:
  description: Send a request to Olarm to set area 8 to sleep on your alarm.

zone_8_stay:
  description: Send a request to Olarm to set area 8 to stay on your alarm.

zone_8_disarm:
  description: Send a request to Olarm to disarm area 8 of your alarm.

bypass_zone:
  description: Send a request to Olarm to bypass the zone on your alarm.
  fields:
    zone_num:
      description: "Zone Number"
      example: "1"
      required: true
