zone_1_arm:
  description: Send a request to Olarm to arm zone 1 on your alarm.

zone_1_sleep:
  description: Send a request to Olarm to set zone 1 to sleep on your alarm.

zone_1_stay:
  description: Send a request to Olarm to set zone 1 to stay on your alarm.

zone_1_disarm:
  description: Send a request to Olarm to disarm zone 1 of your alarm.

zone_2_arm:
  description: Send a request to Olarm to arm zone 2 on your alarm.

zone_2_sleep:
  description: Send a request to Olarm to set zone 2 to sleep on your alarm.

zone_2_stay:
  description: Send a request to Olarm to set zone 2 to stay on your alarm.

zone_2_disarm:
  description: Send a request to Olarm to disarm zone 2 of your alarm.
