blank_issues_enabled: false
contact_links:
  - name: olarm-ha-integration GitHub Community Support
    url: https://github.com/rainepretorius/olarm-ha-integration/discussions
    about: Please ask and answer questions here.
